spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/flyway
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    url: jdbc:mysql://localhost:3306/flyway
    user: root
    password: 1234


  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true

